fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '1.1.1'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.1.1'
    epel:
      repo: 'https://github.com/stahnma/puppet-module-epel.git'
      ref: '1.0.0'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '1.1.3'
    gcc:
      repo: 'https://github.com/puppetlabs/puppetlabs-gcc.git'
      ref: '0.2.0'
    git:
      repo: 'https://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.2.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.1.3'
    profile_passenger:
      repo: 'https://github.com/eshamow/eshamow-profile_passenger.git'
      ref: '0.2.5'
    passenger:
      repo: 'https://github.com/eshamow/puppetlabs-passenger'
      ref: '270bf462a9942f5c534684bef2767cedb98707a0'
    postgresql:
      repo: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
      ref: '4.0.0'
    puppetdb:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
      ref: '4.0.0'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: '734a33bb7f7670136e77179aafeeebb81d8d14d3'
    r10k:
      repo: 'https://github.com/acidprime/r10k.git'
      ref: 'v2.3.0'
    vcsrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: '1.1.0'
  symlinks:
    puppetmaster: "#{source_dir}"
