fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.1.0'
    apache:
      repo: 'https://github.com/puppetlabs/puppetlabs-apache.git'
      ref: '525667d09f5ba1c886ae4440ca31357384699aa9'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: '1.1.1'
    epel:
      repo: 'https://github.com/stahnma/puppet-module-epel.git'
      ref: '1.0.0'
    firewall:
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '955024ee846a251686f70505c4502ac406cfe4d4'
    gcc:
      repo: 'https://github.com/puppetlabs/puppetlabs-gcc.git'
      ref: '0.2.0'
    git:
      repo: 'https://github.com/puppetlabs/puppetlabs-git.git'
      ref: '0.2.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.1.3'
    profile_passenger:
      repo: 'https://github.com/eshamow/eshamow-profile_passenger.git'
      ref: '85c139cd30591b602fec73f4113ad5d7064c576d'
    passenger:
      repo: 'https://github.com/eshamow/puppetlabs-passenger'
      ref: '09d181a2a818b177db106917c87327a0d8593dbb'
    postgresql:
      repo: 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
      ref: '4.0.0'
    puppetboard:
      repo: 'https://github.com/puppet-community/puppet-module-puppetboard'
      ref: '69b545d2a253c3a12ef0076190620c3f6b585256'
    puppetdb:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppetdb.git'
      ref: '4.0.0'
    python:
      repo: 'https://github.com/stankevich/puppet-python.git'
      ref: '1.7.10'
    ruby:
      repo: 'https://github.com/puppetlabs/puppetlabs-ruby.git'
      ref: '734a33bb7f7670136e77179aafeeebb81d8d14d3'
    r10k:
      repo: 'https://github.com/acidprime/r10k.git'
      ref: 'v2.3.0'
    vcsrepo:
      repo: 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref: '1.1.0'
  symlinks:
    puppetmaster: "#{source_dir}"
