# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.define "master" do |master|
    master.vm.box = "opscode_centos-6.5_chef-provisionerless"
    master.vm.network "private_network", ip: "192.168.33.10"
  end
  config.vm.define "ubu10" do |ubu10|
    ubu10.vm.box = "opscode_ubuntu-10.04_chef-provisionerless"
    ubu10.vm.network "private_network", ip: "192.168.33.20"
    ubu10.vm.provision "shell",
      inline: "sudo rm -Rf /var/lib/apt/lists/* && apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-precise.deb && dpkg -i ./puppetlabs-release-precise.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "ubu12" do |ubu12|
    ubu12.vm.box = "opscode_ubuntu-12.04_chef-provisionerless"
    ubu12.vm.network "private_network", ip: "192.168.33.21"
    ubu12.vm.provision "shell",
      inline: "sudo rm -Rf /var/lib/apt/lists/* && apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-precise.deb && dpkg -i ./puppetlabs-release-precise.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "ubu14" do |ubu14|
    ubu14.vm.box = "opscode_ubuntu-14.04_chef-provisionerless"
    ubu14.vm.network "private_network", ip: "192.168.33.22"
    ubu14.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && dpkg -i ./puppetlabs-release-trusty.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "deb6" do |deb6|
    deb6.vm.box = "opscode_debian-6.0.10_chef-provisionerless"
    deb6.vm.network "private_network", ip: "192.168.33.23"
    deb6.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-squeeze.deb && dpkg -i ./puppetlabs-release-squeeze.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "deb7" do |deb7|
    deb7.vm.box = "opscode_debian-7.6_chef-provisionerless"
    deb7.vm.network "private_network", ip: "192.168.33.24"
    deb7.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-wheezy.deb && dpkg -i ./puppetlabs-release-wheezy.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "el5" do |el5|
    el5.vm.box = "opscode_centos-5.10_chef-provisionerless"
    el5.vm.network "private_network", ip: "192.168.33.25"
    el5.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm && yum -y install puppet"
  end
  config.vm.define "el6" do |el6|
    el6.vm.box = "opscode_centos-6.5_chef-provisionerless"
    el6.vm.network "private_network", ip: "192.168.33.26"
    el6.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm && yum -y install puppet"
  end
  config.vm.define "el7" do |el7|
    el7.vm.box = "opscode_centos-7.0_chef-provisionerless"
    el7.vm.network "private_network", ip: "192.168.33.27"
    el7.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm && yum -y install puppet"
  end

  # 32 BIT
  config.vm.define "ubu10_i386" do |ubu10_i386|
    ubu10_i386.vm.box = "opscode_ubuntu-10.04-i386_chef-provisionerless"
    ubu10_i386.vm.network "private_network", ip: "192.168.33.20"
    ubu10_i386.vm.provision "shell",
      inline: "sudo rm -Rf /var/lib/apt/lists/* && apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-precise.deb && dpkg -i ./puppetlabs-release-precise.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "ubu12_i386" do |ubu12_i386|
    ubu12_i386.vm.box = "opscode_ubuntu-12.04-i386_chef-provisionerless"
    ubu12_i386.vm.network "private_network", ip: "192.168.33.21"
    ubu12_i386.vm.provision "shell",
      inline: "sudo rm -Rf /var/lib/apt/lists/* && apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-precise.deb && dpkg -i ./puppetlabs-release-precise.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "ubu14_i386" do |ubu14_i386|
    ubu14_i386.vm.box = "opscode_ubuntu-14.04-i386_chef-provisionerless"
    ubu14_i386.vm.network "private_network", ip: "192.168.33.22"
    ubu14_i386.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-trusty.deb && dpkg -i ./puppetlabs-release-trusty.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "deb6_i386" do |deb6_i386|
    deb6_i386.vm.box = "opscode_debian-6.0.10-i386_chef-provisionerless"
    deb6_i386.vm.network "private_network", ip: "192.168.33.23"
    deb6_i386.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-squeeze.deb && dpkg -i ./puppetlabs-release-squeeze.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "deb7_i386" do |deb7_i386|
    deb7_i386.vm.box = "opscode_debian-7.6-i386_chef-provisionerless"
    deb7_i386.vm.network "private_network", ip: "192.168.33.24"
    deb7_i386.vm.provision "shell",
      inline: "apt-get install -y curl && curl -O https://apt.puppetlabs.com/puppetlabs-release-wheezy.deb && dpkg -i ./puppetlabs-release-wheezy.deb && apt-get update && apt-get -y install puppet"
  end
  config.vm.define "el5_i386" do |el5_i386|
    el5_i386.vm.box = "opscode_centos-5.10-i386_chef-provisionerless"
    el5_i386.vm.network "private_network", ip: "192.168.33.25"
    el5_i386.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm && yum -y install puppet"
  end
  config.vm.define "el6_i386" do |el6_i386|
    el6_i386.vm.box = "opscode_centos-6.5-i386_chef-provisionerless"
    el6_i386.vm.network "private_network", ip: "192.168.33.26"
    el6_i386.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm && yum -y install puppet"
  end
  config.vm.define "el7_i386" do |el7_i386|
    el7_i386.vm.box = "opscode_centos-7.0-i386_chef-provisionerless"
    el7_i386.vm.network "private_network", ip: "192.168.33.27"
    el7_i386.vm.provision "shell",
      inline: "rpm -ivh http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm && yum -y install puppet"
  end


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
  end
  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # Enable provisioning with CFEngine. CFEngine Community packages are
  # automatically installed. For example, configure the host as a
  # policy server and optionally a policy file to run:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.am_policy_hub = true
  #   # cf.run_file = "motd.cf"
  # end
  #
  # You can also configure and bootstrap a client to an existing
  # policy server:
  #
  # config.vm.provision "cfengine" do |cf|
  #   cf.policy_server_address = "10.0.2.15"
  # end

  # Enable provisioning with Puppet stand alone.  Puppet manifests
  # are contained in a directory path relative to this Vagrantfile.
  # You will need to create the manifests directory and a manifest in
  # the file default.pp in the manifests_path directory.
  #
  # config.vm.provision "puppet" do |puppet|
  #   puppet.manifests_path = "manifests"
  #   puppet.manifest_file  = "site.pp"
  # end

  # Enable provisioning with chef solo, specifying a cookbooks path, roles
  # path, and data_bags path (all relative to this Vagrantfile), and adding
  # some recipes and/or roles.
  #
  # config.vm.provision "chef_solo" do |chef|
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { mysql_password: "foo" }
  # end

  # Enable provisioning with chef server, specifying the chef server URL,
  # and the path to the validation key (relative to this Vagrantfile).
  #
  # The Opscode Platform uses HTTPS. Substitute your organization for
  # ORGNAME in the URL and validation key.
  #
  # If you have your own Chef Server, use the appropriate URL, which may be
  # HTTP instead of HTTPS depending on your configuration. Also change the
  # validation key to validation.pem.
  #
  # config.vm.provision "chef_client" do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #
  # If you're using the Opscode platform, your validator client is
  # ORGNAME-validator, replacing ORGNAME with your organization name.
  #
  # If you have your own Chef Server, the default validation client name is
  # chef-validator, unless you changed the configuration.
  #
  #   chef.validation_client_name = "ORGNAME-validator"
end
